#!/usr/bin/env python
# -*-coding: utf8 -*-

import sys
import pygtk
pygtk.require('2.0')
import pynotify

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print >>sys.stderr, "Usage: %s title message" % sys.argv[0]
        exit(1)

    title = sys.argv[1]
    message = sys.argv[2]

    pynotify.init("Notification")
    n = pynotify.Notification(title, message)
    n.set_urgency(pynotify.URGENCY_CRITICAL)
    n.set_timeout(30000)    # 30 seconds
    n.show()

