#!/bin/bash

latex_tpl=./pandoc.tpl

[ $# -ge 1 ] || {
    echo "Usage: $0 filename" && exit
}

name=$(echo $1|sed "s/\.[^.]*$//g")

rm $name.aux  $name.dvi  $name.log  $name.out  $name.pdf  $name.ps  $name.toc

pandoc -fmarkdown -tlatex -s --toc --template=$latex_tpl -o $name.tex $1

xelatex $name.tex
xelatex $name.tex
